# Generated by Django 3.2.19 on 2026-06-06 00:00

from django.db import migrations, models
import uuid
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20260602_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, db_index=True),
        ),
        migrations.CreateModel(
            name='EmailTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('template_name', models.CharField(max_length=255)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('retrying', 'Retrying'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_attempt_at', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailtask',
            index=models.Index(fields=['status', 'next_attempt_at'], name='movies_emailtask_status_next_a_14fc0e_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtask',
            index=models.Index(fields=['recipient'], name='movies_emailtask_recipient_2da4d4_idx'),
        ),
    ]
