# Generated by Django 3.2.19 on 2026-06-11 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20260606_2037'),
        ('movies', '0004_booking_email_queue'),
    ]

    operations = [
    ]
