# Generated by Django 3.2.19 on 2026-07-01 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0005_merge_20260611_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='reserved', max_length=12)),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=100)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='emailtask',
            name='movies_emailtask_status_next_a_14fc0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailtask',
            name='movies_emailtask_recipient_2da4d4_idx',
        ),
        migrations.AddField(
            model_name='booking',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(db_index=True, default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_embed_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.theater'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['movie', 'booked_at'], name='movies_book_movie_i_323598_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['theater', 'booked_at'], name='movies_book_theater_a2fd03_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtask',
            index=models.Index(fields=['status', 'next_attempt_at'], name='movies_emai_status_77f8ab_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtask',
            index=models.Index(fields=['recipient'], name='movies_emai_recipie_9a07f9_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['theater', 'is_booked'], name='movies_seat_theater_7e5f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['seat_number'], name='movies_seat_seat_nu_66ec54_idx'),
        ),
        migrations.AddField(
            model_name='seatreservation',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='seatreservation',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='movies.seat'),
        ),
        migrations.AddField(
            model_name='seatreservation',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to='movies.theater'),
        ),
        migrations.AddField(
            model_name='seatreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['status', 'expires_at'], name='movies_seat_status_ca000a_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['seat', 'status'], name='movies_seat_seat_id_f2f2b6_idx'),
        ),
    ]
