# Generated by Codex on 2026-07-17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='gateway_order_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='gateway_payment_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_provider',
            field=models.CharField(default='razorpay', max_length=32),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtask',
            name='deduplication_key',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='razorpay', max_length=32)),
                ('event_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('gateway_order_id', models.CharField(blank=True, default='', max_length=100)),
                ('gateway_payment_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='processed', max_length=16)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['gateway_order_id', 'event_type'], name='movies_pay_gateway_b48b11_idx'),
                    models.Index(fields=['gateway_payment_id'], name='movies_pay_gateway_b9a69c_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('provider', 'event_id'), name='unique_payment_gateway_event'),
                ],
            },
        ),
    ]
