# Generated by Django 3.2.19 on 2026-07-17 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_booking_and_reservation_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='paymentwebhookevent',
            name='movies_pay_gateway_b48b11_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentwebhookevent',
            name='movies_pay_gateway_b9a69c_idx',
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['gateway_order_id', 'event_type'], name='movies_paym_gateway_2c95ba_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['gateway_payment_id'], name='movies_paym_gateway_2414d8_idx'),
        ),
        migrations.AddField(
            model_name='emailevent',
            name='email_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='movies.emailtask'),
        ),
    ]
